dist: trusty
sudo: false
language: python
python:
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
addons:
  apt:
    packages:
    - libgraph-easy-perl
before_install:
- if [[ $TRAVIS_PYTHON_VERSION = 3.2 ]]; then if_pygments=:; fi
install:
- pip install pydiatra pyflakes
- $if_pygments pip install docutils pygments
script:
- ./dothost www.iana.org > iana.dot
- cat iana.dot
- graph-easy --as boxart < iana.dot
- python3 -m pydiatra .
- python3 -m pyflakes .
- $if_pygments private/check-rst

# vim:ts=2 sts=2 sw=2 et
