.\" Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
.\" SPDX-License-Identifier: MIT

.TH DOTHOST 1 2019-03-16 "dothost 0.2.1" ""
.SH NAME
dothost \- DNS lookup with Graphviz output
.SH SYNOPSIS
.SY dothost
.I ADDRESS
.RI [ ADDRESS \&.\|.\|.\&]
.YS
.SH DESCRIPTION
.B dothost
is a DNS lookup utility,
which produces output in Graphviz format.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show help message and exit.
.TP
.B \-\-version
Show version information and exit.
.SH EXAMPLES
.EX
.RB "$ " "dothost www.iana.org | graph-easy \-\-as boxart > file.boxart"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as html > file.html"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as svg > file.svg"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as dot > file.dot"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as txt > file.txt"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as vcg > file.vcg"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as gdl > file.gdl"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as graphml > file.graphml"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as gif > file.gif"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as jpg > file.jpg"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as pdf > file.pdf"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as png > file.png"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as ps > file.ps"
.RB "$ " "dothost www.iana.org | graph-easy \-\-as ascii"

       +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
       v                         |
     #####################     +\-\-\-\-\-\-\-\-\-\-\-\-+
  +> #   www.iana.org    # \-\-> | 192.0.32.8 |
  |  #####################     +\-\-\-\-\-\-\-\-\-\-\-\-+
  |    |
  |    |
  |    v
  |  +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
  +\- | 2620:0:2d0:200::8 |
     +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
.EE
.SH SEE ALSO
.BR graphviz (7),
.BR host (1),
.BR gethostbyaddr (3),
.BR getaddrinfo (3)
